VERSION 0.6

ARG BASE_IMAGE=ubuntu:22.04

build-image:
  ARG TARGETPLATFORM
  ARG TARGETOS
  ARG TARGETARCH
  ARG TARGETVARIANT

  FROM $BASE_IMAGE
  
  ENV DEBIAN_FRONTEND=noninteractive
  RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      gnupg \
      software-properties-common \
    && add-apt-repository ppa:oibaf/test \
    && apt-get update

  ## Bootloader stuff, platform-specific
  RUN echo "TARGET ARCH: ${TARGETARCH}"
  IF [ "$TARGETARCH" = "amd64" ]
    RUN apt install -y --no-install-recommends \
      grub-pc-bin \
      grub-efi-amd64-bin \
      grub-efi-amd64-signed \
      grub2 \
      grub2-common \
      && apt-get clean
  ELSE IF [ "$TARGETARCH" = "arm64" ]
    RUN apt install -y --no-install-recommends \
      grub-common \
      grub-efi-arm64-bin \
      grub-efi-arm64-signed \
      grub-efi-arm64 \
      grub2-common \
      && apt-get clean
  END

  ## Other platform-specific packages
  IF [ "$TARGETARCH" = "amd64" ]
    RUN apt install -y --no-install-recommends \
      thermald \
      && apt-get clean
  ELSE IF [ "$TARGETARCH" = "arm64" ]
    RUN echo "nothing for apt to do yet"
  END
      

  RUN apt install -y \
    binutils \
    bzip2 \
    conntrack \
    console-data \
    console-setup \
    coreutils \
    cryptsetup \
    curl \
    debianutils \
    dmsetup \
    dosfstools \
    dracut \
    dracut-live \
    dracut-network \
    e2fsprogs \
    efibootmgr \
    ethtool \
    firmware-sof-signed \
    fuse3 \
    gawk \
    haveged \
    iproute2 \
    iptables \
    isc-dhcp-common \
    jq \
    kbd \
    libatm1 \
    libfile-fcntllock-perl \
    libldap-common \
    liblocale-gettext-perl \
    libnss-systemd \
    libpam-cap \
    libsasl2-modules \
    linux-image-generic-hwe-22.04 \
    lldpd \
    lvm2 \
    mdadm \
    nano \
    nbd-client \
    ncurses-term \
    neovim \
    networkd-dispatcher \
    nfs-common \
    open-iscsi \
    open-vm-tools \
    openssh-server \
    os-prober \
    packagekit-tools \
    parted \
    pigz \
    polkitd \
    publicsuffix \
    python3-neovim \
    rsync \
    shared-mime-info \
    snapd \
    snmpd \
    squashfs-tools \
    ssh-import-id \
    sudo \
    systemd \
    systemd-hwe-hwdb \
    systemd-timesyncd \
    unattended-upgrades \
    xauth \
    xclip \
    xdg-user-dirs \
    xxd \
    xz-utils \
    zerofree \
  && rm -rf /var/lib/apt/lists/*

  RUN ln -s /usr/sbin/grub-install /usr/sbin/grub2-install
  RUN ln -s /usr/bin/grub-editenv /usr/bin/grub2-editenv
  RUN systemctl enable systemd-networkd
  RUN systemctl enable ssh

  # Enable tmp
  RUN cp -v /usr/share/systemd/tmp.mount /etc/systemd/system/ 
  RUN systemctl enable tmp.mount

  # Fixup sudo perms
  RUN chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo


  # Clear cache
  RUN apt-get clean && rm -rf /var/cache/* && journalctl --vacuum-size=1K && rm /etc/machine-id && rm /var/lib/dbus/machine-id && rm /etc/hostname
  