VERSION 0.6

ARG BASE_IMAGE=ubuntu:22.04

build-image:
  ARG TARGETPLATFORM
  ARG TARGETOS
  ARG TARGETARCH
  ARG TARGETVARIANT

  FROM $BASE_IMAGE
  
  ENV DEBIAN_FRONTEND=noninteractive
  RUN apt update
  RUN apt install -y software-properties-common
  RUN add-apt-repository ppa:oibaf/test
  RUN apt update

  ## Bootloader stuff, platform-specific
  RUN echo "TARGET ARCH: ${TARGETARCH}"
  IF [ "$TARGETARCH" = "amd64" ]
    RUN apt install -y \
      grub-pc-bin \
      grub-efi-amd64-bin \
      grub2 \
      grub2-common \
      && apt-get clean
  ELSE IF [ "$TARGETARCH" = "arm64" ]
    RUN apt install -y \
      grub-common \
      grub-efi-arm64-bin \
      grub-efi-arm64-signed \
      grub-efi-arm64 \
      grub2-common
  END

  RUN apt install -y \
    systemd \
    nohang \
    sudo \
    iproute2 \
    squashfs-tools \
    parted dracut \
    dracut-network dracut-live tar \
    e2fsprogs \
    dosfstools \
    coreutils \
    debianutils \
    curl \
    openssh-server \
    nano \
    gawk \
    haveged \
    rsync \
    jq \
    neovim \
    open-vm-tools \
    snapd \
    conntrack \
    iptables \
    linux-image-generic-hwe-22.04 && apt-get clean

  RUN ln -s /usr/sbin/grub-install /usr/sbin/grub2-install
  RUN ln -s /usr/bin/grub-editenv /usr/bin/grub2-editenv
  RUN systemctl enable nohang-desktop.service
  RUN systemctl enable systemd-networkd
  RUN systemctl enable ssh
  RUN echo "auto lo" > /etc/network/interfaces
  RUN echo "iface lo inet loopback" >> /etc/network/interfaces

  # Enable tmp
  RUN cp -v /usr/share/systemd/tmp.mount /etc/systemd/system/ 
  RUN systemctl enable tmp.mount

  # Fixup sudo perms
  RUN chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo


  # Clear cache
  RUN apt-get clean && rm -rf /var/cache/* && journalctl --vacuum-size=1K && rm /etc/machine-id && rm /var/lib/dbus/machine-id
  