cosign: false
verify: false
install:
  grub-entry-name: "Edge Node OS"
  system:
    size: 3000
  recovery-system:
    size: 3000
upgrade:
  grub-entry-name: "Edge Node OS"
  recovery-system:
    size: 3000
  system:
    size: 3000
reset:
  grub-entry-name: "Edge Node OS"
  system:
    size: 3000