---

name: Earthly Manual Jobs

on:
  workflow_dispatch:
    inputs:
      earthly-target:
        description: "Build Target in Earthfile"
        required: true
        type: string
      runs-on:
        required: true
        description: "Runner Class"
        default: ubuntu-latest
        type: choice
        options:
        - ubuntu-latest
        - buildjet-2vcpu-ubuntu-2204
        - buildjet-4vcpu-ubuntu-2204
        - buildjet-8vcpu-ubuntu-2204
        - buildjet-16vcpu-ubuntu-2204
        - buildjet-32vcpu-ubuntu-2204
        - buildjet-2vcpu-ubuntu-2204-arm
        - buildjet-4vcpu-ubuntu-2204-arm
        - buildjet-8vcpu-ubuntu-2204-arm
        - buildjet-16vcpu-ubuntu-2204-arm
        - buildjet-32vcpu-ubuntu-2204-arm


env:
  REGISTRY: ghcr.io

jobs:
  earthly:
    runs-on: ${{ github.event.inputs.runs-on }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      
      - name: Run Earthly
        run: earthly -P --push +${{ github.event.inputs.earthly-target }}

      - name: Export build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: edgenode-build-${{ github.event.inputs.earthly-target }}
          path: "build/*"