---

name: Edgenode Image Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  framework-image-build:
    runs-on: ${{ matrix.arch == 'arm64' && 'buildjet-4vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        flavor:
        # - alpine
        - ubuntu
        os:
        - linux
        arch:
        - amd64
        - arm64
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Image Base Name
        run: |
          echo "IMAGE_NAME=framework-${{ matrix.flavor }}-${{ matrix.arch }}" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:buildx-stable-1
      
      - name: Login to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,prefix=,format=long

      # TODO: Also sign images with cosign
      - name: Build and push Framework image
        uses: docker/build-push-action@v3
        with:
          file: framework/Dockerfile.${{ matrix.flavor }}
          context: ""
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save framework image tags as artifact
        run: |
          cat <<EOF > ${{ env.IMAGE_NAME }}-oci.txt
          ${{ steps.meta.outputs.tags }}
          EOF

      - name: Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}-oci
          path: "*-oci.txt"

  edgenode-image-build:
    runs-on: ${{ matrix.arch == 'arm64' && 'buildjet-4vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}
    needs: framework-image-build
    strategy:
      fail-fast: false
      matrix:
        flavor:
        # - alpine
        # - alpine-rpi
        - ubuntu
        - ubuntu-rpi
        os:
        - linux
        arch:
        - amd64
        - arm64
        exclude:
        - flavor: alpine-rpi
          arch: amd64
        - flavor: ubuntu-rpi
          arch: amd64

        # TODO: temporary excludes until more work is done to build arm64 ubuntu images
        # - flavor: ubuntu
        #   arch: arm64
        # - flavor: ubuntu-rpi
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set image base name
        run: |
          echo "IMAGE_NAME=edgenode-${{ matrix.flavor }}-${{ matrix.arch }}" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:buildx-stable-1
      
      - name: Login to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate long sha for framework image ref
        id: sha
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,format=long

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,prefix=,format=long

      - name: Inform OS Label (release)
        if: github.event_name == 'release'
        run: |
          echo "OS_LABEL=latest" >> $GITHUB_ENV

      - name: Inform OS Label (pull request)
        if: github.event_name == 'pull_request'
        run: |
          echo "OS_LABEL=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      
      - name: Inform OS Label (main)
        if: github.event_name != 'pull_request' && github.event_name != 'release' && github.ref == 'refs/heads/main'
        run: |
          echo "OS_LABEL=main" >> $GITHUB_ENV

      # TODO: Also sign images with cosign
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: images/Dockerfile.${{ matrix.flavor }}
          context: ""
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          build-args: |
            TARGETOS=${{ matrix.os }}
            TARGETARCH=${{ matrix.arch }}
            FRAMEWORK_IMAGE_TAG=${{ steps.sha.outputs.version }}
            OS_VERSION=${{ steps.meta.outputs.version }}
            FLAVOR=${{ matrix.flavor }}
            GITHUB_REPO=${{ github.repository }}
            BUG_REPORT_URL=${{ github.repositoryUrl }}/issues
            HOME_URL=${{ github.repositoryUrl }}
            OS_REPO=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            OS_LABEL=${{ env.OS_LABEL }}

      - name: Save image tags as artifact
        run: |
          cat <<EOF > ${{ env.IMAGE_NAME }}-oci.txt
          ${{ steps.meta.outputs.tags }}
          EOF

      - name: Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}-oci
          path: "*-oci.txt"

  edgenode-image-iso:
    runs-on: ${{ matrix.arch == 'arm64' && 'buildjet-4vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}
    needs: edgenode-image-build
    strategy:
      fail-fast: false
      matrix:
        flavor:
        # - alpine
        - ubuntu
        arch:
        - amd64
        - arm64
        # exclude:
        # - flavor: ubuntu
        #   arch: arm64
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/edgenode-${{ matrix.flavor }}-${{ matrix.arch }}
          tags: |
            type=sha,prefix=,format=long
      
      - name: Pull Image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}

      - name: Configure ISO manifest
        run: |
          cat <<EOF > manifest.yaml
          name: "edgenode-${{ matrix.flavor }}-${{ matrix.arch }}"
          arch: "${{ (matrix.arch == 'amd64') && 'x86_64' || matrix.arch }}"
          debug: true

          iso:
            # Packages to be installed in the rootfs
            rootfs:
            - docker:${{ steps.meta.outputs.tags }}
            # Packages to be installed in the uefi image
            uefi:
            - channel:live/grub2-efi-image
            # Packages to be installed in the iso image
            image:
            - channel:live/grub2-efi-image
            - channel:live/grub2
            - dir:/cOS/overlay/files-iso
            label: "COS_LIVE"
            
          repositories:
            - uri: quay.io/costoolkit/releases-teal${{ (matrix.arch == 'arm64') && '-arm64' || '' }}
              arch: ${{ (matrix.arch == 'amd64') && 'x86_64' || matrix.arch }}
          EOF

      - name: Build ISO
        run: |
          docker run -v $PWD:/cOS -v /var/run/docker.sock:/var/run/docker.sock -i --rm --entrypoint=/usr/bin/elemental quay.io/kairos/osbuilder-tools:v0.1.1 --config-dir=/cOS/ build-iso --date=false --local --debug --output /cOS/

      - name: Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edgenode-${{ matrix.flavor }}-${{ matrix.arch }}-iso
          path: "*.iso"

  edgenode-image-rpi:
    runs-on: ubuntu-latest
    needs: edgenode-image-build
    strategy:
      fail-fast: false
      matrix:
        flavor:
        # - alpine-rpi
        - ubuntu-rpi
        arch:
        - arm64
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout elemental-toolkit
        uses: actions/checkout@v3
        with:
          repository: rancher/elemental-toolkit
          path: elemental-toolkit
      
      - name: Configure Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/edgenode-${{ matrix.flavor }}-${{ matrix.arch }}
          tags: |
            type=sha,prefix=,format=long

      - name: Pull Image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}

      - name: Download luet
        run: |
          id=$(docker create quay.io/luet/base:0.32.4)
          sudo docker cp $id:/usr/bin/luet /usr/bin/luet
          docker rm -v $id

      - name: Download elemental CLI
        run: |
          id=$(docker create quay.io/costoolkit/elemental-cli:v0.0.15-8a78e6b)
          sudo docker cp $id:/usr/bin/elemental /usr/bin/elemental
          docker rm -v $id

      - name: Build RPi Image
        env:
          MODEL: rpi64
          IMAGE_NAME: edgenode-${{ matrix.flavor }}-${{ matrix.arch }}.img
          STATE_SIZE: "6200"
          RECOVERY_SIZE: "4200"
          SIZE: "15200"
          DEFAULT_ACTIVE_SIZE: "2000"
        run: |
          sudo apt install -y gdisk kpartx
          mkdir -p elemental-toolkit/build
          (cd elemental-toolkit && sudo images/arm-img-builder.sh --model $MODEL --docker-image ${{ steps.meta.outputs.tags }} build/$IMAGE_NAME && mv build ../)

      - name: packaging
        env:
          IMAGE_NAME: edgenode-${{ matrix.flavor }}-${{ matrix.arch }}.img
        run: |
          sudo xz -v build/$IMAGE_NAME

      - name: Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edgenode-${{ matrix.flavor }}-${{ matrix.arch }}-img
          path: "build/*"

  edgenode-image-release:
    runs-on: ubuntu-latest
    needs:
    - edgenode-image-build
    - edgenode-image-iso
    - edgenode-image-rpi
    if: github.event_name == 'release'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: download

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "edgenode-*/*"
          overwrite: true
          update_latest_release: true
          tags: true