---

name: Edgenode Image ISO

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  edgenode-image-iso:
    runs-on: ubuntu-latest
    needs: edgenode-image-build
    strategy:
      fail-fast: false
      matrix:
        include:
        - variant: alpine
        - variant: ubuntu
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/edgenode-${{ matrix.variant }}
          tags: |
            type=sha
      
      - name: Pull Image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}

      - name: Build ISO
        run: |
          docker run -v $PWD:/cOS -v /var/run/docker.sock:/var/run/docker.sock -i --rm quay.io/kairos/osbuilder-tools:v0.1.1 --name "edgenode-${{ matrix.variant }}" --debug build-iso --date=false --local --overlay-iso /cOS/overlay/files-iso ${{ steps.meta.outputs.tags }} --output /cOS/

      - name: Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edgenode-${{ matrix.variant }}-iso
          path: "*.iso"