---

name: Elemental ISO Disk Image

on:
  push:

env:
  IMAGE: ghcr.io/jtcressy-home/edge-images-elemental:main

jobs:
  elemental-iso:
    runs-on: ubuntu-latest
    name: elemental-iso
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup cloud-init
        working-directory: ./elemental
        run: |
          cat <<EOF > files-iso/config.yaml
          #node-config
          install:
            device: "/dev/sda"
            reboot: true
            poweroff: false
            auto: true
          EOF
      
      - name: Pull Image
        working-directory: ./elemental
        run: |
          docker pull $IMAGE

      - name: Build ISO with $IMAGE
        working-directory: ./elemental
        run: |
          docker run -v $PWD:/cOS -v /var/run/docker.sock:/var/run/docker.sock -i --rm quay.io/kairos/osbuilder-tools:v0.1.1 --name "custom-iso" --debug build-iso --date=false --local --overlay-iso /cOS/files-iso $IMAGE --output /cOS/

      - name: Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: "elemental/*.iso"