name: "Show tailscale status on tty1"
stages:
  initramfs:
    - if: |
        [ -f "/etc/inittab" ]
      commands:
      - set -i -e 's/tty1.*//g' /etc/inittab
      - echo "tty1::respawn:/bin/bash -c \"while true; do clear; cat /etc/issue; tailscale status; (tailscale status --json | jq -r '.AuthURL' | qrencode -t ANSI); sleep 5; done;\"" >> /etc/inittab