name: "Configure persistent dirs bind-mounts"
stages:
  rootfs.after:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/modprobe.d
          /etc/rancher
          /etc/sysconfig
          /etc/runlevels
          /etc/ssh
          /etc/iscsi 
          /etc/cni
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/rancher
          /var/lib/kubelet
          /var/lib/wicked
          /var/lib/longhorn
          /var/lib/cni
          /var/lib/tailscale
          /var/lib/containerd
        PERSISTENT_STATE_BIND: "true"
    - if: |
        cat /proc/cmdline | grep -q "kairos.boot_live_mode"
      name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/rancher
          /etc/sysconfig
          /etc/runlevels
          /etc/ssh
          /etc/iscsi 
          /etc/cni
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/rancher
          /var/lib/kubelet
          /var/lib/wicked
          /var/lib/longhorn
          /var/lib/cni
          /var/lib/tailscale
          /var/lib/containerd
        PERSISTENT_STATE_BIND: "true"
    - if: '[ ! -f /dev/disk/by-label/COS_OEM ]'
      name: "Redirect /oem to COS_GRUB if COS_OEM does not exist"
      commands:
      - sed -i "s/COS_OEM/COS_GRUB/g" /run/cos/cos-layout.env
    - if: '[ ! -f /run/cos/recovery_mode ] && [ ! -f /run/cos/live_mode ]'
      name: "Grow persistent"
      layout:
        device:
          label: COS_PERSISTENT
        expand_partition:
          # Size 0 is required to specify all remaining space
          size: 0
  boot:
  - if: "[ ! -d /usr/local/cloud-config ]"
    commands:
    - mkdir /usr/local/cloud-config
    - chmod 600 /usr/local/cloud-config
    name: "Ensure /usr/local/cloud-config exists"